/**
 * regroup-cards.ts
 * Moves every card from the 6 Prego chapter sets into the 19 Notte topics
 * (lib/paths.ts). Card ids never change, so progress rows survive.
 *
 * Run: npx tsx scripts/regroup-cards.ts            (dry run: reads only)
 *      npx tsx scripts/regroup-cards.ts --confirm  (writes)
 *
 * Every run backs up sets, cards and sentences to backups/<timestamp>.json
 * and writes backups/<timestamp>-regroup.sql, the same change as one
 * transaction with its own checks, for running in the Supabase SQL Editor
 * instead of --confirm.
 */
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import { randomUUID } from 'crypto'
import { mkdirSync, writeFileSync } from 'fs'
import { PATHS, type TopicSlug } from '../lib/paths'
import { EXPECTED_TOPIC_COUNTS, planRegroup, type LiveCard, type RegroupPlan } from './lib/regroup-plan'
dotenv.config({ path: '.env.local', quiet: true })

const CONFIRM = process.argv.includes('--confirm')

const db = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

interface SetRow { id: string; title: string; description: string | null; category: string; sort_order: number }
interface SentenceRow { id: string; set_id: string | null; card_id: string | null; type: string }
interface TopicTarget { slug: TopicSlug; title: string; description: string; category: string; sortOrder: number; id: string; exists: boolean }

const isChapterSet = (s: SetRow) => s.category === 'general' && /^Chapter \d+\b/.test(s.title)

function fail(message: string): never {
  console.error(`\n✗ ${message}`)
  process.exit(1)
}

async function load() {
  const [sets, cards, sentences, progress] = await Promise.all([
    db.from('sets').select('*').order('sort_order'),
    db.from('cards').select('*').order('sort_order').range(0, 9999),
    db.from('sentences').select('*').range(0, 9999),
    db.from('progress').select('*', { count: 'exact', head: true }),
  ])
  for (const r of [sets, cards, sentences, progress]) if (r.error) throw r.error
  return {
    sets: sets.data as SetRow[],
    cards: cards.data as (LiveCard & Record<string, unknown>)[],
    sentences: sentences.data as SentenceRow[],
    progressCount: progress.count ?? 0,
  }
}

function topicTargets(sets: SetRow[]): TopicTarget[] {
  let sortOrder = 0
  return PATHS.flatMap(path => path.topics.map(topic => {
    const existing = sets.find(s => s.category === path.category && s.title === topic.title)
    return {
      slug: topic.slug,
      title: topic.title,
      description: topic.en,
      category: path.category,
      sortOrder: ++sortOrder,
      id: existing?.id ?? randomUUID(),
      exists: Boolean(existing),
    }
  }))
}

function printPlan(plan: RegroupPlan, targets: TopicTarget[], total: number) {
  for (const path of PATHS) {
    const n = path.topics.reduce((sum, t) => sum + plan.counts[t.slug], 0)
    console.log(`\n${path.name.it} · ${path.category}`.padEnd(42) + String(n).padStart(4))
    for (const topic of path.topics) {
      const actual = plan.counts[topic.slug]
      const expected = EXPECTED_TOPIC_COUNTS[topic.slug]
      const mark = actual === expected ? '✓' : '✗'
      const target = targets.find(t => t.slug === topic.slug)!
      const note = actual === expected ? '' : `  expected ${expected}`
      console.log(`  ${mark} ${topic.title.padEnd(26)} ${String(actual).padStart(4)}   ${target.exists ? 'exists' : 'create'}${note}`)
    }
  }
  console.log(`\nMatched ${plan.assignments.length}/${total} cards`)
}

const sqlText = (s: string | null) => (s === null ? 'NULL' : `'${s.replace(/'/g, "''")}'`)

function buildSql(opts: {
  targets: TopicTarget[]
  plan: RegroupPlan
  repoint: { id: string; setId: string }[]
  deleteSentenceIds: string[]
  chapterSets: SetRow[]
  totalCards: number
  progressCount: number
}): string {
  const { targets, plan, repoint, deleteSentenceIds, chapterSets, totalCards, progressCount } = opts
  const topicId = (slug: TopicSlug) => targets.find(t => t.slug === slug)!.id
  const chapterIds = chapterSets.map(s => sqlText(s.id)).join(', ')
  const newTopics = targets.filter(t => !t.exists)
  const lines: string[] = [
    '-- Generated by scripts/regroup-cards.ts. Moves every card into its Notte topic.',
    '-- One transaction: any failed check rolls the whole thing back.',
    'BEGIN;',
    '',
  ]

  if (newTopics.length > 0) {
    lines.push('-- 1. The topic sets')
    lines.push('INSERT INTO sets (id, title, description, category, sort_order) VALUES')
    lines.push(newTopics.map(t =>
      `  (${sqlText(t.id)}, ${sqlText(t.title)}, ${sqlText(t.description)}, ${sqlText(t.category)}, ${t.sortOrder})`
    ).join(',\n') + ';', '')
  }

  lines.push('-- 2. Every card into its topic (ids unchanged, so progress survives)')
  lines.push('UPDATE cards AS c SET set_id = v.set_id::uuid, sort_order = v.sort_order')
  lines.push('FROM (VALUES')
  lines.push(...plan.assignments.map((a, i) => {
    const comma = i < plan.assignments.length - 1 ? ',' : ''
    return `  (${sqlText(a.cardId)}, ${sqlText(topicId(a.topic))}, ${a.sortOrder})${comma}  -- ${a.italian.replace(/\s+/g, ' ')}`
  }))
  lines.push(') AS v(id, set_id, sort_order)')
  lines.push('WHERE c.id = v.id::uuid;', '')

  if (repoint.length > 0) {
    lines.push("-- 3. Card-level sentences follow their card's topic")
    lines.push('UPDATE sentences AS s SET set_id = v.set_id::uuid')
    lines.push('FROM (VALUES')
    lines.push(repoint.map(r => `  (${sqlText(r.id)}, ${sqlText(r.setId)})`).join(',\n'))
    lines.push(') AS v(id, set_id)')
    lines.push('WHERE s.id = v.id::uuid;', '')
  }

  if (deleteSentenceIds.length > 0) {
    lines.push('-- 4. Chapter-scoped sentences (they regenerate per topic)')
    lines.push(`DELETE FROM sentences WHERE id IN (\n  ${deleteSentenceIds.map(sqlText).join(',\n  ')}\n);`, '')
  }

  if (chapterSets.length > 0) {
    lines.push('-- 5. The chapter sets, only if they are empty (deleting a set cascades to its cards)')
    lines.push('DO $$ BEGIN')
    lines.push(`  IF EXISTS (SELECT 1 FROM cards WHERE set_id IN (${chapterIds})) THEN`)
    lines.push("    RAISE EXCEPTION 'A chapter set still has cards; nothing was changed';")
    lines.push('  END IF;')
    lines.push('END $$;')
    lines.push(`DELETE FROM sets WHERE id IN (${chapterIds});`, '')
  }

  lines.push('-- 6. Checks')
  lines.push('DO $$ BEGIN')
  lines.push(`  IF (SELECT count(*) FROM cards) <> ${totalCards} THEN RAISE EXCEPTION 'Card count changed'; END IF;`)
  lines.push(`  IF (SELECT count(*) FROM progress) <> ${progressCount} THEN RAISE EXCEPTION 'Progress count changed'; END IF;`)
  lines.push("  IF EXISTS (SELECT 1 FROM cards c LEFT JOIN sets s ON s.id = c.set_id WHERE s.id IS NULL) THEN RAISE EXCEPTION 'A card has no set'; END IF;")
  for (const t of targets) {
    lines.push(`  IF (SELECT count(*) FROM cards WHERE set_id = ${sqlText(t.id)}) <> ${plan.counts[t.slug]} THEN RAISE EXCEPTION ${sqlText(`Wrong count in ${t.title}`)}; END IF;`)
  }
  lines.push('END $$;', '', 'COMMIT;', '')
  return lines.join('\n')
}

async function write(opts: {
  targets: TopicTarget[]
  plan: RegroupPlan
  repoint: { id: string; setId: string }[]
  deleteSentenceIds: string[]
  chapterSets: SetRow[]
}) {
  const { targets, plan, repoint, deleteSentenceIds, chapterSets } = opts
  const topicId = (slug: TopicSlug) => targets.find(t => t.slug === slug)!.id

  const newTopics = targets.filter(t => !t.exists)
  if (newTopics.length > 0) {
    const { error } = await db.from('sets').insert(newTopics.map(t => ({
      id: t.id, title: t.title, description: t.description, category: t.category, sort_order: t.sortOrder,
    })))
    if (error) throw error
  }
  console.log(`  ✓ ${newTopics.length} topic sets created`)

  let moved = 0
  for (let i = 0; i < plan.assignments.length; i += 10) {
    const batch = plan.assignments.slice(i, i + 10)
    const results = await Promise.all(batch.map(a =>
      db.from('cards').update({ set_id: topicId(a.topic), sort_order: a.sortOrder }).eq('id', a.cardId)
    ))
    for (const r of results) if (r.error) throw r.error
    moved += batch.length
  }
  console.log(`  ✓ ${moved} cards moved`)

  for (const r of repoint) {
    const { error } = await db.from('sentences').update({ set_id: r.setId }).eq('id', r.id)
    if (error) throw error
  }
  console.log(`  ✓ ${repoint.length} card-level sentences re-pointed`)

  if (deleteSentenceIds.length > 0) {
    const { error } = await db.from('sentences').delete().in('id', deleteSentenceIds)
    if (error) throw error
  }
  console.log(`  ✓ ${deleteSentenceIds.length} chapter sentences deleted`)

  const chapterIds = chapterSets.map(s => s.id)
  if (chapterIds.length > 0) {
    const { count, error: countErr } = await db.from('cards').select('*', { count: 'exact', head: true }).in('set_id', chapterIds)
    if (countErr) throw countErr
    if (count !== 0) fail(`${count} cards are still in chapter sets; not deleting them. Re-run to retry.`)
    const { error } = await db.from('sets').delete().in('id', chapterIds)
    if (error) throw error
  }
  console.log(`  ✓ ${chapterIds.length} chapter sets deleted`)
}

async function main() {
  console.log(`Regroup: chapter sets → Notte topics${CONFIRM ? '' : '   (DRY RUN: nothing is written to the database)'}`)

  const before = await load()
  const chapterSets = before.sets.filter(isChapterSet)
  console.log(`\nLive: ${before.sets.length} sets · ${before.cards.length} cards · ${before.progressCount} progress rows · ${before.sentences.length} sentences`)

  const plan = planRegroup(before.cards)
  const targets = topicTargets(before.sets)
  printPlan(plan, targets, before.cards.length)

  if (!plan.ok) {
    for (const c of plan.unmatched) console.error(`  unmatched: ${c.italian} (ch ${c.chapter}, ${c.word_type}, ${c.id})`)
    for (const k of plan.duplicates) console.error(`  duplicate: ${k}`)
    for (const m of plan.countMismatches) console.error(`  ${m.topic}: expected ${m.expected}, got ${m.actual}`)
    fail('The mapping does not cover every card. Nothing was written.')
  }

  const chapterSetIds = new Set(chapterSets.map(s => s.id))
  const stranded = before.cards.filter(c => chapterSetIds.has(c.set_id) && !plan.assignments.some(a => a.cardId === c.id))
  if (stranded.length > 0) fail(`${stranded.length} cards would be left in chapter sets. Nothing was written.`)

  const topicOfCard = new Map(plan.assignments.map(a => [a.cardId, a.topic]))
  const chapterSentences = before.sentences.filter(s => s.set_id && chapterSetIds.has(s.set_id))
  const deleteSentenceIds = chapterSentences.filter(s => !s.card_id).map(s => s.id)
  const repoint = chapterSentences.filter(s => s.card_id).map(s => {
    const topic = topicOfCard.get(s.card_id!)
    if (!topic) fail(`Sentence ${s.id} belongs to card ${s.card_id}, which is not in the plan.`)
    return { id: s.id, cardId: s.card_id!, setId: targets.find(t => t.slug === topic)!.id }
  })

  console.log('\nSentences')
  console.log(`  delete   ${deleteSentenceIds.length} chapter-scoped (regenerate per topic)`)
  console.log(`  re-point ${repoint.length} card-level to their card's topic`)
  for (const r of repoint) {
    const card = before.cards.find(c => c.id === r.cardId)!
    console.log(`           ${card.italian} → ${targets.find(t => t.id === r.setId)!.title}`)
  }
  const untouched = before.sentences.length - chapterSentences.length
  if (untouched > 0) console.log(`  keep     ${untouched} outside the chapter sets`)

  console.log(`\nChapter sets to delete once empty: ${chapterSets.length}`)
  for (const s of chapterSets) {
    console.log(`  ${s.title} (${before.cards.filter(c => c.set_id === s.id).length} cards → 0)`)
  }

  const chapters = new Map<number | null, number>()
  for (const c of before.cards) chapters.set(c.chapter, (chapters.get(c.chapter) ?? 0) + 1)
  console.log(`\nChapter tags (unchanged): ${[...chapters].sort().map(([ch, n]) => `cap. ${ch} ${n}`).join(' · ')}`)

  const stamp = new Date().toISOString().replace(/[:.]/g, '-')
  mkdirSync('backups', { recursive: true })
  const backupPath = `backups/${stamp}.json`
  writeFileSync(backupPath, JSON.stringify({ sets: before.sets, cards: before.cards, sentences: before.sentences }, null, 2))
  const sqlPath = `backups/${stamp}-regroup.sql`
  writeFileSync(sqlPath, buildSql({
    targets, plan, repoint, deleteSentenceIds, chapterSets,
    totalCards: before.cards.length, progressCount: before.progressCount,
  }))
  console.log(`\nBackup: ${backupPath}`)
  console.log(`SQL:    ${sqlPath} (one transaction; an alternative to --confirm)`)

  if (!CONFIRM) {
    console.log('\nDry run complete. Nothing was written to the database. Re-run with --confirm to apply.')
    return
  }

  console.log('\nWriting…')
  await write({ targets, plan, repoint, deleteSentenceIds, chapterSets })

  const after = await load()
  const setIds = new Set(after.sets.map(s => s.id))
  const orphans = after.cards.filter(c => !c.set_id || !setIds.has(c.set_id))
  console.log('\nChecks')
  console.log(`  ${after.progressCount === before.progressCount ? '✓' : '✗'} progress rows: ${after.progressCount} (was ${before.progressCount})`)
  console.log(`  ${after.cards.length === before.cards.length ? '✓' : '✗'} cards: ${after.cards.length} (was ${before.cards.length})`)
  console.log(`  ${orphans.length === 0 ? '✓' : '✗'} cards without a set: ${orphans.length}`)
  if (after.progressCount !== before.progressCount || after.cards.length !== before.cards.length || orphans.length > 0) {
    fail(`Post-write checks failed. Restore from ${backupPath}.`)
  }
  console.log('\nDone.')
}

main().catch(err => { console.error(err); process.exit(1) })
