import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

const db = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const SETS = [
  {
    title: 'The Alphabet',
    description: 'Italian has 21 letters — J, K, W, X, and Y are not native',
    category: 'alphabet',
    sort_order: 0,
    cards: [
      { italian: 'A', english: 'a (ah)' },
      { italian: 'B', english: 'bi (bee)' },
      { italian: 'C', english: 'ci (chee)' },
      { italian: 'D', english: 'di (dee)' },
      { italian: 'E', english: 'e (ay)' },
      { italian: 'F', english: 'effe (ef-feh)' },
      { italian: 'G', english: 'gi (jee)' },
      { italian: 'H', english: 'acca (ak-kah)' },
      { italian: 'I', english: 'i (ee)' },
      { italian: 'L', english: 'elle (el-leh)' },
      { italian: 'M', english: 'emme (em-meh)' },
      { italian: 'N', english: 'enne (en-neh)' },
      { italian: 'O', english: 'o (oh)' },
      { italian: 'P', english: 'pi (pee)' },
      { italian: 'Q', english: 'cu (koo)' },
      { italian: 'R', english: 'erre (er-reh)' },
      { italian: 'S', english: 'esse (es-seh)' },
      { italian: 'T', english: 'ti (tee)' },
      { italian: 'U', english: 'u (oo)' },
      { italian: 'V', english: 'vu (voo)' },
      { italian: 'Z', english: 'zeta (zeh-tah)' },
    ],
  },
  {
    title: 'Numbers 1–20',
    description: 'Count from one to twenty',
    category: 'numbers',
    sort_order: 1,
    cards: [
      { italian: 'uno', english: 'one' },
      { italian: 'due', english: 'two' },
      { italian: 'tre', english: 'three' },
      { italian: 'quattro', english: 'four' },
      { italian: 'cinque', english: 'five' },
      { italian: 'sei', english: 'six' },
      { italian: 'sette', english: 'seven' },
      { italian: 'otto', english: 'eight' },
      { italian: 'nove', english: 'nine' },
      { italian: 'dieci', english: 'ten' },
      { italian: 'undici', english: 'eleven' },
      { italian: 'dodici', english: 'twelve' },
      { italian: 'tredici', english: 'thirteen' },
      { italian: 'quattordici', english: 'fourteen' },
      { italian: 'quindici', english: 'fifteen' },
      { italian: 'sedici', english: 'sixteen' },
      { italian: 'diciassette', english: 'seventeen' },
      { italian: 'diciotto', english: 'eighteen' },
      { italian: 'diciannove', english: 'nineteen' },
      { italian: 'venti', english: 'twenty' },
    ],
  },
  {
    title: 'Numbers 21–100',
    description: 'Tens, patterns, and key compound numbers',
    category: 'numbers',
    sort_order: 2,
    cards: [
      { italian: 'ventuno', english: 'twenty-one' },
      { italian: 'ventidue', english: 'twenty-two' },
      { italian: 'ventitrè', english: 'twenty-three' },
      { italian: 'ventiquattro', english: 'twenty-four' },
      { italian: 'venticinque', english: 'twenty-five' },
      { italian: 'ventisei', english: 'twenty-six' },
      { italian: 'ventisette', english: 'twenty-seven' },
      { italian: 'ventotto', english: 'twenty-eight' },
      { italian: 'ventinove', english: 'twenty-nine' },
      { italian: 'trenta', english: 'thirty' },
      { italian: 'trentuno', english: 'thirty-one' },
      { italian: 'quaranta', english: 'forty' },
      { italian: 'quarantacinque', english: 'forty-five' },
      { italian: 'cinquanta', english: 'fifty' },
      { italian: 'cinquantadue', english: 'fifty-two' },
      { italian: 'sessanta', english: 'sixty' },
      { italian: 'sessantasei', english: 'sixty-six' },
      { italian: 'settanta', english: 'seventy' },
      { italian: 'settantasette', english: 'seventy-seven' },
      { italian: 'ottanta', english: 'eighty' },
      { italian: 'ottantotto', english: 'eighty-eight' },
      { italian: 'novanta', english: 'ninety' },
      { italian: 'novantanove', english: 'ninety-nine' },
      { italian: 'cento', english: 'one hundred' },
    ],
  },
  {
    title: 'Common Verbs',
    description: '50 essential Italian verbs in infinitive form',
    category: 'verbs',
    sort_order: 3,
    cards: [
      { italian: 'essere', english: 'to be' },
      { italian: 'avere', english: 'to have' },
      { italian: 'fare', english: 'to do / to make' },
      { italian: 'andare', english: 'to go' },
      { italian: 'venire', english: 'to come' },
      { italian: 'parlare', english: 'to speak' },
      { italian: 'mangiare', english: 'to eat' },
      { italian: 'bere', english: 'to drink' },
      { italian: 'dormire', english: 'to sleep' },
      { italian: 'lavorare', english: 'to work' },
      { italian: 'studiare', english: 'to study' },
      { italian: 'leggere', english: 'to read' },
      { italian: 'scrivere', english: 'to write' },
      { italian: 'ascoltare', english: 'to listen' },
      { italian: 'guardare', english: 'to watch / to look' },
      { italian: 'capire', english: 'to understand' },
      { italian: 'sapere', english: 'to know (a fact)' },
      { italian: 'potere', english: 'to be able to / can' },
      { italian: 'volere', english: 'to want' },
      { italian: 'dovere', english: 'to have to / must' },
      { italian: 'stare', english: 'to stay / to be (health)' },
      { italian: 'prendere', english: 'to take' },
      { italian: 'dare', english: 'to give' },
      { italian: 'vedere', english: 'to see' },
      { italian: 'sentire', english: 'to hear / to feel' },
      { italian: 'aprire', english: 'to open' },
      { italian: 'chiudere', english: 'to close' },
      { italian: 'arrivare', english: 'to arrive' },
      { italian: 'partire', english: 'to leave / to depart' },
      { italian: 'tornare', english: 'to return' },
      { italian: 'comprare', english: 'to buy' },
      { italian: 'vendere', english: 'to sell' },
      { italian: 'pagare', english: 'to pay' },
      { italian: 'trovare', english: 'to find' },
      { italian: 'mettere', english: 'to put' },
      { italian: 'portare', english: 'to bring / to wear' },
      { italian: 'usare', english: 'to use' },
      { italian: 'camminare', english: 'to walk' },
      { italian: 'correre', english: 'to run' },
      { italian: 'giocare', english: 'to play' },
      { italian: 'cantare', english: 'to sing' },
      { italian: 'ballare', english: 'to dance' },
      { italian: 'cucinare', english: 'to cook' },
      { italian: 'pulire', english: 'to clean' },
      { italian: 'aiutare', english: 'to help' },
      { italian: 'pensare', english: 'to think' },
      { italian: 'credere', english: 'to believe' },
      { italian: 'ricordare', english: 'to remember' },
      { italian: 'dimenticare', english: 'to forget' },
      { italian: 'provare', english: 'to try' },
    ],
  },
  {
    title: 'People & Family',
    description: 'Family members and people words',
    category: 'nouns',
    sort_order: 4,
    cards: [
      { italian: 'la madre / la mamma', english: 'mother / mom' },
      { italian: 'il padre / il papà', english: 'father / dad' },
      { italian: 'il figlio', english: 'son' },
      { italian: 'la figlia', english: 'daughter' },
      { italian: 'il fratello', english: 'brother' },
      { italian: 'la sorella', english: 'sister' },
      { italian: 'il nonno', english: 'grandfather' },
      { italian: 'la nonna', english: 'grandmother' },
      { italian: 'il nipote', english: 'grandson / nephew' },
      { italian: 'la nipote', english: 'granddaughter / niece' },
      { italian: 'lo zio', english: 'uncle' },
      { italian: 'la zia', english: 'aunt' },
      { italian: 'il marito', english: 'husband' },
      { italian: 'la moglie', english: 'wife' },
      { italian: 'il bambino', english: 'child / boy' },
      { italian: 'la bambina', english: 'girl (child)' },
      { italian: "l'uomo", english: 'man' },
      { italian: 'la donna', english: 'woman' },
      { italian: 'il ragazzo', english: 'boy / young man' },
      { italian: 'la ragazza', english: 'girl / young woman' },
      { italian: "l'amico", english: 'friend (male)' },
      { italian: "l'amica", english: 'friend (female)' },
      { italian: 'il collega', english: 'colleague' },
      { italian: 'il vicino', english: 'neighbor' },
      { italian: 'la persona', english: 'person' },
      { italian: 'la gente', english: 'people' },
      { italian: 'la famiglia', english: 'family' },
      { italian: 'il parente', english: 'relative' },
      { italian: 'il cugino', english: 'cousin (male)' },
      { italian: 'la cugina', english: 'cousin (female)' },
    ],
  },
  {
    title: 'Food & Drink',
    description: 'Essential food and drink vocabulary',
    category: 'nouns',
    sort_order: 5,
    cards: [
      { italian: 'il pane', english: 'bread' },
      { italian: 'la pasta', english: 'pasta' },
      { italian: 'la pizza', english: 'pizza' },
      { italian: 'il riso', english: 'rice' },
      { italian: 'la carne', english: 'meat' },
      { italian: 'il pesce', english: 'fish' },
      { italian: 'il pollo', english: 'chicken' },
      { italian: "l'insalata", english: 'salad' },
      { italian: 'la verdura', english: 'vegetables' },
      { italian: 'la frutta', english: 'fruit' },
      { italian: 'il formaggio', english: 'cheese' },
      { italian: "l'uovo", english: 'egg' },
      { italian: 'il burro', english: 'butter' },
      { italian: "l'olio", english: 'oil' },
      { italian: 'il sale', english: 'salt' },
      { italian: 'il pepe', english: 'pepper' },
      { italian: 'lo zucchero', english: 'sugar' },
      { italian: 'il latte', english: 'milk' },
      { italian: "l'acqua", english: 'water' },
      { italian: 'il vino', english: 'wine' },
      { italian: 'la birra', english: 'beer' },
      { italian: 'il caffè', english: 'coffee' },
      { italian: 'il tè', english: 'tea' },
      { italian: 'il succo', english: 'juice' },
      { italian: 'la colazione', english: 'breakfast' },
      { italian: 'il pranzo', english: 'lunch' },
      { italian: 'la cena', english: 'dinner' },
      { italian: "l'antipasto", english: 'appetizer / starter' },
      { italian: 'il primo', english: 'first course' },
      { italian: 'il dolce', english: 'dessert / sweet' },
    ],
  },
  {
    title: 'Around the House',
    description: 'Rooms and household objects',
    category: 'nouns',
    sort_order: 6,
    cards: [
      { italian: 'la casa', english: 'house / home' },
      { italian: "l'appartamento", english: 'apartment' },
      { italian: 'la camera', english: 'bedroom / room' },
      { italian: 'la cucina', english: 'kitchen' },
      { italian: 'il bagno', english: 'bathroom' },
      { italian: 'il salotto', english: 'living room' },
      { italian: 'il giardino', english: 'garden' },
      { italian: 'la porta', english: 'door' },
      { italian: 'la finestra', english: 'window' },
      { italian: 'il tavolo', english: 'table' },
      { italian: 'la sedia', english: 'chair' },
      { italian: 'il letto', english: 'bed' },
      { italian: 'il divano', english: 'sofa / couch' },
      { italian: "l'armadio", english: 'wardrobe / closet' },
      { italian: 'la lampada', english: 'lamp' },
      { italian: 'il telefono', english: 'phone' },
      { italian: 'il computer', english: 'computer' },
      { italian: 'la televisione', english: 'television' },
      { italian: 'il frigorifero', english: 'refrigerator' },
      { italian: 'la lavatrice', english: 'washing machine' },
      { italian: 'la chiave', english: 'key' },
      { italian: 'la scala', english: 'stairs / ladder' },
      { italian: 'il garage', english: 'garage' },
      { italian: 'il balcone', english: 'balcony' },
      { italian: 'il tetto', english: 'roof' },
    ],
  },
  {
    title: 'Greetings & Phrases',
    description: 'Essential phrases for everyday conversation',
    category: 'phrases',
    sort_order: 7,
    cards: [
      { italian: 'Ciao', english: 'Hello / Goodbye (informal)' },
      { italian: 'Buongiorno', english: 'Good morning' },
      { italian: 'Buonasera', english: 'Good evening' },
      { italian: 'Buonanotte', english: 'Good night' },
      { italian: 'Arrivederci', english: 'Goodbye (formal)' },
      { italian: 'Come stai?', english: 'How are you? (informal)' },
      { italian: 'Come sta?', english: 'How are you? (formal)' },
      { italian: 'Bene, grazie', english: 'Fine, thank you' },
      { italian: 'Per favore', english: 'Please' },
      { italian: 'Grazie', english: 'Thank you' },
      { italian: 'Prego', english: "You're welcome" },
      { italian: 'Scusa', english: 'Sorry / Excuse me (informal)' },
      { italian: 'Mi scusi', english: 'Excuse me (formal)' },
      { italian: 'Sì', english: 'Yes' },
      { italian: 'No', english: 'No' },
      { italian: 'Forse', english: 'Maybe' },
      { italian: 'Non capisco', english: "I don't understand" },
      { italian: 'Parla inglese?', english: 'Do you speak English?' },
      { italian: 'Come si chiama?', english: 'What is your name? (formal)' },
      { italian: 'Mi chiamo...', english: 'My name is...' },
      { italian: 'Piacere', english: 'Nice to meet you' },
      { italian: 'Quanto costa?', english: 'How much does it cost?' },
      { italian: "Dov'è...?", english: 'Where is...?' },
      { italian: 'Aiuto!', english: 'Help!' },
      { italian: 'Non lo so', english: "I don't know" },
    ],
  },
  {
    title: 'Colors & Adjectives',
    description: 'Colors and common descriptive words',
    category: 'adjectives',
    sort_order: 8,
    cards: [
      { italian: 'rosso', english: 'red' },
      { italian: 'blu', english: 'blue' },
      { italian: 'verde', english: 'green' },
      { italian: 'giallo', english: 'yellow' },
      { italian: 'arancione', english: 'orange' },
      { italian: 'viola', english: 'purple' },
      { italian: 'rosa', english: 'pink' },
      { italian: 'bianco', english: 'white' },
      { italian: 'nero', english: 'black' },
      { italian: 'grigio', english: 'gray' },
      { italian: 'marrone', english: 'brown' },
      { italian: 'grande', english: 'big / large' },
      { italian: 'piccolo', english: 'small / little' },
      { italian: 'bello', english: 'beautiful / handsome' },
      { italian: 'brutto', english: 'ugly' },
      { italian: 'buono', english: 'good' },
      { italian: 'cattivo', english: 'bad' },
      { italian: 'nuovo', english: 'new' },
      { italian: 'vecchio', english: 'old' },
      { italian: 'lungo', english: 'long' },
      { italian: 'corto', english: 'short (length)' },
      { italian: 'alto', english: 'tall / high' },
      { italian: 'basso', english: 'short / low' },
      { italian: 'caldo', english: 'hot / warm' },
      { italian: 'freddo', english: 'cold' },
    ],
  },
  {
    title: 'Days, Months & Seasons',
    description: 'Days of the week, months, and seasons',
    category: 'time',
    sort_order: 9,
    cards: [
      { italian: 'lunedì', english: 'Monday' },
      { italian: 'martedì', english: 'Tuesday' },
      { italian: 'mercoledì', english: 'Wednesday' },
      { italian: 'giovedì', english: 'Thursday' },
      { italian: 'venerdì', english: 'Friday' },
      { italian: 'sabato', english: 'Saturday' },
      { italian: 'domenica', english: 'Sunday' },
      { italian: 'gennaio', english: 'January' },
      { italian: 'febbraio', english: 'February' },
      { italian: 'marzo', english: 'March' },
      { italian: 'aprile', english: 'April' },
      { italian: 'maggio', english: 'May' },
      { italian: 'giugno', english: 'June' },
      { italian: 'luglio', english: 'July' },
      { italian: 'agosto', english: 'August' },
      { italian: 'settembre', english: 'September' },
      { italian: 'ottobre', english: 'October' },
      { italian: 'novembre', english: 'November' },
      { italian: 'dicembre', english: 'December' },
      { italian: 'la primavera', english: 'spring' },
    ],
  },
]

async function main() {
  console.log('Seeding database…')

  for (const setData of SETS) {
    const { cards, ...setMeta } = setData

    const { data: existing } = await db
      .from('sets')
      .select('id')
      .eq('title', setMeta.title)
      .maybeSingle()

    if (existing) {
      console.log(`  Skipping "${setMeta.title}" — already exists`)
      continue
    }

    const { data: newSet, error: setError } = await db
      .from('sets')
      .insert(setMeta)
      .select()
      .single()

    if (setError || !newSet) {
      console.error(`  Error creating set "${setMeta.title}":`, setError)
      continue
    }

    const cardRows = cards.map((c, i) => ({
      set_id: newSet.id,
      italian: c.italian,
      english: c.english,
      sort_order: i,
    }))

    const { error: cardError } = await db.from('cards').insert(cardRows)
    if (cardError) {
      console.error(`  Error inserting cards for "${setMeta.title}":`, cardError)
    } else {
      console.log(`  ✓ "${setMeta.title}" — ${cards.length} cards`)
    }
  }

  console.log('Done.')
  process.exit(0)
}

main().catch(err => { console.error(err); process.exit(1) })
